---
format: 
  revealjs:
    navigation-mode: vertical
    slide-number: true
    width: 1600
    height: 900
    logo: "images/revelo.png"
    footer: "[home page](https://revelo-rnaseq.github.io/2024_RNASeq_website/)"
    css: ["css/theme.css", "css/custom.css"]
    theme: simple
    controls: true
mainfont: "Times New Roman"
editor: source
filters:
  - roughnotation
editor_options: 
  chunk_output_type: inline
---

##  {#TitleSlide data-menu-title="TitleSlide" background-image="images/back001.jpg" background-size="cover" background-opacity="0.3"}

```{r setup, include=FALSE}
library(fontawesome)
library(tidyverse)
library(quarto)
```

::: {style="position: absolute; left: 180px; top: 200px; height: 525px; width: 1500px; background-color: #69b1e9; padding: 20px; padding-left: 50px; border-radius: 5px;"}
[Visualizzazione Dati]{style="font-size: 100px; font-weight: bold; line-height: 1em; margin: 0px;"}

[Esplorare e Comunicare i Risultati]{style="font-size: 50px;font-weight: bold;"}

<br> <br>

[Analisi Bulk RNA-Seq per Dottorandi]{style="font-size: 40px; font-weight: bold;"}
:::

#  {background-image="images/back001.jpg" background-size="cover" background-opacity="0.1"}

[Quality Control Grafico]{.tit .p-span-center}

##  {background-image="images/back001.jpg" background-size="cover" background-opacity="0.1"}

[PCA - Principal Component Analysis]{.subtit}

"Come si raggruppano i miei campioni?"
- I replicati biologici dovrebbero essere vicini.
- Il trattamento dovrebbe essere la principale fonte di varianza (PC1).
- Utile per identificare **Outliers**.

Necessario trasformare i dati prima (VST o rlog) per renderli omoschedastici.

```r
vsd <- vst(dds, blind=FALSE) # Variance Stabilizing Transformation
plotPCA(vsd, intgroup=c("condition", "batch"))
```

##  {background-image="images/back001.jpg" background-size="cover" background-opacity="0.1"}

[MA Plot]{.subtit}

"La normalizzazione ha funzionato?"
- Asse X: Media dei conteggi (A = Average).
- Asse Y: Log2 Fold Change (M = Minus, log ratio).
- Ci aspettiamo che la nuvola di punti sia centrata su Y=0.
- Evidenzia l'effetto del **LFC Shrinkage** sui geni a bassa espressione.

```r
plotMA(resLFC, ylim=c(-5,5))
```

#  {background-image="images/back001.jpg" background-size="cover" background-opacity="0.1"}

[Visualizzare i Risultati]{.tit .p-span-center}

##  {background-image="images/back001.jpg" background-size="cover" background-opacity="0.1"}

[Volcano Plot]{.subtit}

Visualizzazione "classica" dei DEG (Differentially Expressed Genes).
- Asse X: Log2 Fold Change (Magnitude).
- Asse Y: -log10(Adjusted P-value) (Significance).
- I geni più interessanti sono in alto a destra (Up + Signif) e alto a sinistra (Down + Signif).

```r
library(EnhancedVolcano)
EnhancedVolcano(res,
    lab = rownames(res),
    x = 'log2FoldChange',
    y = 'padj')
```

##  {background-image="images/back001.jpg" background-size="cover" background-opacity="0.1"}

[Heatmap]{.subtit}

"Chi va su e chi giù insieme?"
- Visualizzare i top geni (es. top 20 o 50 per varianza o p-value).
- Usare dati trasformati (VST).
- Clustering gerarchico per raggruppare geni o campioni simili.

```r
library(pheatmap)
topGenes <- head(order(res$padj), 20)
mat <- assay(vsd)[topGenes, ]
mat <- mat - rowMeans(mat) # Centrare per vedere deviazioni dalla media
pheatmap(mat, annotation_col=df_metadata)
```

#  {background-image="images/qmark.jpg" background-size="cover" background-opacity="0.7"}

::: {style="position: absolute; left: 980px; top: 450px;"}
[Domande?]{style="font-size: 130px; font-weight: bold; color: white"}
:::
